# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matvecmult_eigen <- function(A, b, n_cores) {
    .Call(`_boostCopula_matvecmult_eigen`, A, b, n_cores)
}

matTvecmult_eigen <- function(A, b, n_cores) {
    .Call(`_boostCopula_matTvecmult_eigen`, A, b, n_cores)
}

matmatTmult_eigen <- function(A, B, n_cores) {
    .Call(`_boostCopula_matmatTmult_eigen`, A, B, n_cores)
}

